"""add is_connected column in user model

Revision ID: 076cb241ad69
Revises: f91e3d63374f
Create Date: 2020-02-09 21:44:57.612225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076cb241ad69'
down_revision = 'f91e3d63374f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_connected', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_connected')

    # ### end Alembic commands ###
