"""add pinned channels for user

Revision ID: 07c94f1da80b
Revises: 1859a8ce10eb
Create Date: 2020-03-20 22:53:49.836591

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07c94f1da80b'
down_revision = '1859a8ce10eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('channel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'],
                                            name=op.f('fk_pins_channel_id_channels')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f('fk_pins_user_id_users')),
                    sa.PrimaryKeyConstraint('user_id', 'channel_id', name=op.f('pk_pins'))
                    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('size',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('size',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    op.drop_table('pins')
    # ### end Alembic commands ###
