"""add new fields in user, channel, file models

Revision ID: 1859a8ce10eb
Revises: 7c8754e7e3dd
Create Date: 2020-03-16 22:21:04.605226

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1859a8ce10eb'
down_revision = '7c8754e7e3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=64),
                              type_=sa.String(length=20),
                              existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_channels_creator_id_users'), 'users',
                                    ['creator_id'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer()))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_timestamp')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_channels_creator_id_users'), type_='foreignkey')
        batch_op.alter_column('name',
                              existing_type=sa.String(length=20),
                              type_=sa.VARCHAR(length=64),
                              existing_nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('description')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
