"""create channel and message models, add relationships in user model

Revision ID: 6ba748b54610
Revises: 246fec369862
Create Date: 2020-02-05 23:20:13.372585

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6ba748b54610'
down_revision = '246fec369862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
                    sa.UniqueConstraint('name', name=op.f('uq_channels_name'))
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('channel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'],
                                            name=op.f('fk_messages_channel_id_channels')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f('fk_messages_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
                    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_channel_id_channels'), 'users', 'channels', ['channel_id'],
                          ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_channel_id_channels'), 'users', type_='foreignkey')
    op.drop_column('users', 'channel_id')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('channels')
    # ### end Alembic commands ###
