"""delete field last_seen in user model, change text field in message model

Revision ID: 7c8754e7e3dd
Revises: db1cd67f08bd
Create Date: 2020-03-01 16:37:49.458169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c8754e7e3dd'
down_revision = 'db1cd67f08bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('text',
                              existing_type=sa.TEXT(),
                              nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('text',
                              existing_type=sa.TEXT(),
                              nullable=False)

    # ### end Alembic commands ###
