"""create file model

Revision ID: d152d8e7e032
Revises: 076cb241ad69
Create Date: 2020-02-25 19:05:32.167285

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd152d8e7e032'
down_revision = '076cb241ad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=300), nullable=False),
                    sa.Column('content', sa.LargeBinary(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
                    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_file_id_files'), 'files', ['file_id'],
                                    ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_file_id_files'), type_='foreignkey')
        batch_op.drop_column('file_id')

    op.drop_table('files')
    # ### end Alembic commands ###
