"""create channel and message models, add relationships in user model

Revision ID: f91e3d63374f
Revises: 6c41df0b198f
Create Date: 2020-02-06 18:38:53.313857

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f91e3d63374f'
down_revision = '6c41df0b198f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
                    sa.UniqueConstraint('name', name=op.f('uq_channels_name'))
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('channel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'],
                                            name=op.f('fk_messages_channel_id_channels')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f('fk_messages_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
                    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_channel_id_channels'), 'channels',
                                    ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_channel_id_channels'), type_='foreignkey')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))

    op.drop_table('messages')
    op.drop_table('channels')
    # ### end Alembic commands ###
